devices:
    common: []
    debug: []
    release: []
dockercomposefile:
    common: docker-compose.yml
    debug: ''
    release: ''
extraparms:
    common: {}
    debug: {}
    release: {}
id: 89df4776-e754-4a40-ae80-0515310d0af6
images:
    debug: sha256:11126be8f910cb04e652f253fcaa18f287899fd158d71a3d298d95200231541d
    release: ''
modificationdate: '2020-10-30T11:03:45.582647'
networks:
    common: []
    debug: []
    release: []
platformid: arm64v8-dotnet-50_bullseye
ports:
    common: {}
    debug: {}
    release: {}
privatekey: '-----BEGIN RSA PRIVATE KEY-----

    MIIEpAIBAAKCAQEAoAuG6u+nE5vVoLDA8TcySXFwtEP7jtN0bTVcIeqf42e5Mvq8

    dsWq29v2tbaAYtWDOFGsgbK8S3lD0cb+PAJhPG592d8Z3LlYjIPBOITB/DzhM2ac

    Nl+8KW33l3PDqIxdxP/RlwPN/tyF08wY8SX7Yc/8LmI4aVMS3X0PlqqYQ3DQy8yE

    ItjurXGde2vzQWCwtUkwcycDXJnk0PWSnPLuXxdUBeLQIamxg0/CEvGAFFx6RgSJ

    MwF13Zwgg4Mv1i7MyY6LQsxPlY6YOpeocNVtOYK8tQXm/Yn4IvNH3uCjRChVndmR

    g9lxmVfmzoQW4nfTL7/w7EqlnajfqOv/jDfFZwIDAQABAoIBAFVfML37zqTwGJma

    D6Hcbq+smpEePn8mntFuiFHzRQzaFHl0NLoqoQScplKyInQWLuQI9TtOK5EbA6lQ

    O+eo4VOKIQnqL3KFUA3MbnKGpq+1je+MScHbeZSj+1HHx9QN5CskxxmGRwkvexfK

    pHdmalz3xC696BeO395USs90+rnmCQC0I25KToP4UUAu+ulPa/4xlRk/F/1boQ7g

    VYnmbKtisiZK1VoQMYo+A9rIDNIcZF9lFIKSlxfUjPLfE15CfVTRm0M4HovPEpLk

    IS2H5J4wMRyPO923AHM12zNyCy/26WBaDZ+T8tZi2qJe0AaE3iHDOW+Fk37+rywp

    zwM5TYkCgYEA0GI5QUZFKWmY8uX5IVKZ5sJzPBwJur8FqwCfA8AEDkqYf0nAmsix

    WCWBLNWNfTHgzfBJUDOlmaaW5M+Rb1/nk7VnfGD+Ij80XvRGqJZ8HwdyyqZVmwj7

    Ilq9UJs5YHmCGNumCGJZcZ/C2IJDN/1KS9d9iiWyP5oD6YEcoqhNbdMCgYEAxJ2l

    p7z+4i5VP6TzBy61ws/FCVfwwkgYPUf55/kl+6brtfMdIuFJ3r/MJqxiTtYVfISl

    RtcatC2A2iMmMGd48N2eofDqvsyY9pXrCQ2Mv1rs3egb+e6p/K/Ya6xy9rT80+Ss

    mPGRUqAqPpGL4Dm+OUVmgHG7BVdHCYpNe7ZFCZ0CgYEAt2eL/vBrFNzU+gwArhx2

    Sgygwannwk44Hd6JFhLdPvrWp0lxVIoI1I0F2UEHq8XHl1nCHO2n9ckSi8ZIuZ7O

    QknqECWJ5vh8Doqu2djA28qBdOza8X4BEqaMczJ7WHb5UwmXY0+0a3XyVv6nTNMI

    niHGY110OdhDUzQI0PySUXMCgYB0KnSSi37IoflqNgoE51sqs9lFsPilwTTZGCqW

    HUWMzs2bXf2L+zHK8uUqwFUBIUnmnPSNy0+SvwPPXk8U8D2rijVMluwLORTzNBZ+

    7cuHz6/9WEMXQySaEEc9LtFp4/sxMn2ri6aB+/GZsCLFozg53EA4iXmnKS7mexlW

    i5V0nQKBgQDA06ZsDknveRCLRFPeeNMRJzq+irs2D3KrDWJartPm+55wMAB1tBqP

    gFKaT3FOgCHgoI46FYfqN52bZVM9b42da3YRhZkgQqo4rpoWJpVyC8c97IL+D7r4

    MfauJRYSlvNiZKjQQCX1Q+fQAgcFE/8KqusOyItNHAJXoygU3YLn3A==

    -----END RSA PRIVATE KEY-----

    '
props:
    common:
        appargs: ''
        appname: broccolinator_bl_net
        arg: ''
        buildcommands: ''
        buildfiles: ''
        command: ''
        devpackages: ''
        env: ''
        expose: ''
        extrapackages: ''
        language: dotnet
        preinstallcommands: ''
        runtime: dotnet
        sdkpostinstallcommands: ''
        sdkpreinstallcommands: ''
        targetcommands: ''
        targetfiles: ''
    debug:
        arg: 'ARG SSHUSERNAME=#%application.username%#

            '
    release: {}
publickey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgC4bq76cTm9WgsMDxNzJJcXC0Q/uO03RtNVwh6p/jZ7ky+rx2xarb2/a1toBi1YM4UayBsrxLeUPRxv48AmE8bn3Z3xncuViMg8E4hMH8POEzZpw2X7wpbfeXc8OojF3E/9GXA83+3IXTzBjxJfthz/wuYjhpUxLdfQ+WqphDcNDLzIQi2O6tcZ17a/NBYLC1STBzJwNcmeTQ9ZKc8u5fF1QF4tAhqbGDT8IS8YAUXHpGBIkzAXXdnCCDgy/WLszJjotCzE+Vjpg6l6hw1W05gry1Beb9ifgi80fe4KNEKFWd2ZGD2XGZV+bOhBbid9Mvv/DsSqWdqN+o6/+MN8Vn
sdkimages:
    debug: ''
    release: ''
sdksshaddress: null
shutdownscript:
    common: ''
    debug: ''
    release: ''
startupscript:
    common: ''
    debug: ''
    release: ''
username: torizon
volumes:
    common:
        /tmp: /tmp
    debug:
        /home/torizon/broccolinator_bl_net: /broccolinator_bl_net,rw
    release: {}
